### ISSUE TITLE
Missing Apache Software Lincese 2.0 copy?

### ISSUE THREAD

**Issue by ppisar** [libwww-perl/HTTP-Message#112]
HTTP-Message-6.17 distribution added CONTRIBUTING.md file that is based on an Apache Software License 2.0 (ASL 2.0) licensed work ("This file was adapted from an initial `CONTRIBUTING.mkdn` file from David Golden under the terms of the Apache 2 license").

I believe that 4a section of the license require that any derivative work must provide copy of the license. However I cannot see any such file in the distribution.

**Comment by xdg** [comment]
I hereby allow any CONTRIBUTING.mkdn file from any github.com/dagolden repo to be licensed under the terms of CC0 (https://creativecommons.org/share-your-work/public-domain/cc0/)

**Comment by genio** [comment]
@ppisar Given the above consent of the author, I will alter the verbiage at the bottom of the CONTRIBUTING.md to show that we're adapting his original work under the terms of CC0. Would that satisfy all concerns?

**Comment by ppisar** [comment]
That would be great. I think that should resolve this issue. Thanks.

**Comment by genio** [comment]
Thank you both for pointing this out. The altered file is now in master and will be in a release very soon.

**Comment by genio** [comment]
https://metacpan.org/release/OALDERS/HTTP-Message-6.18 has been released with the fixed wording on the contributing document.  Thanks everyone!
