### ISSUE TITLE
Possibly back out of #125 and #115

### ISSUE THREAD

**Issue by oalders** [libwww-perl/HTTP-Message#127]
```
I think we need to back out of https://github.com/libwww-perl/HTTP-Message/pull/125 and https://github.com/libwww-perl/HTTP-Message/pull/115
5:01 PM 115 introduced problems which 125 tries to fix, but can't completely remedy
5:01 PM So we get more failures than in earlier releases
5:02 PM anyone opposed to reverting those PRs and *then* releasing?
5:03 PM As I recall, to debug this we'd need someone on a Windows machine and using the charset that triggers the errors
```
References PRs: #115 and  #125

**Comment by oalders** [comment]
I don't think we can release a new HTTP::Message without dealing with this.

**Comment by oalders** [comment]
@genio assigned ticket to you as we had discussed Windows testing on IRC.

**Comment by genio** [comment]
IIRC, we are trying to create a Windows-friendly filename right now and we're coming from a UTF-8 world -which Windows isn't when it comes to the file system.

What I think we tossed around was something akin to:

```perl
if ($^O eq 'MSWin32') {
    try {
        require Win32;
        my $fname = Win32::GetANSIPathName($unicode__file_path);
    }
    catch {
        die("We had a problem getting the appropriate Windows-compatible filename: $_");
    };
}
```

I'd need to review that area a bit further to ensure that hand-wavy bit up there is correct.

**Comment by genio** [comment]
@vanHoesel @skaji @karenetheridge Does that make sense? ^^

**Comment by karenetheridge** [comment]
Sure, why not send that out as a -TRIAL release and see what the smokers say?

**Comment by oalders** [comment]
Changes have now been reverted.
