### ISSUE TITLE
[feature request] Support for Brotli Content-Encoding

### ISSUE THREAD

**Issue by trizen** [libwww-perl/HTTP-Message#163]
As more and more websites are moving from Gzip to Brotli compression, it would be nice if `HTTP::Message` would support Brotli encoding (`br`) when [IO::Uncompress::Brotli](https://metacpan.org/pod/IO::Uncompress::Brotli) is installed.

See also: https://en.wikipedia.org/wiki/HTTP_compression

Thanks for considering!

**Comment by oalders** [comment]
That sounds reasonable, if someone would like to implement that.
