### ISSUE TITLE
HTTP::Header content_type_charset dies on idiosyncratic content-type.

### ISSUE THREAD

**Issue by galenhuntington** [libwww-perl/HTTP-Message#167]
A web page I attempted to crawl (https://www.alberta.ca/newsroom/newsroom.cfm?deptID=202) has this unusual header:

`content-type: text/xml; =;charset=UTF-8`

So if I run this code—

```perl
use LWP::UserAgent;
use HTTP::Headers;
my $lwp = LWP::UserAgent->new(
    default_headers =>
        # rejects LWP user agent
        HTTP::Headers->new(user_agent => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36'));
my $resp = $lwp->head('https://www.alberta.ca/newsroom/newsroom.cfm?deptID=202');
print $resp->content_type_charset;
```

—I get this—

```
This should not happen: '=;charset=UTF-8' at /usr/share/perl5/HTTP/Headers/Util.pm line 57.
```

—which brings down my app.

I can just `eval{}` it of course, but it seems there could be a more graceful way of dealing with oddball content-type headers.

**Comment by oalders** [comment]
That's not great. Without really digging in to it you also might be able eto fix up the headers in a `response_header` handler. That doesn't fix the fact that this isn't graceful, but it might be cleaner than an `eval`.

https://metacpan.org/pod/LWP::UserAgent#response_header-=%3E-sub-{-my($response,-$ua,-$handler)-=-@_;-...-}

**Comment by galenhuntington** [comment]
What do you think of replacing the first regex here:
https://github.com/libwww-perl/HTTP-Message/blob/master/lib/HTTP/Headers/Util.pm#L53

with `s/^\s*=?\s*;//`?

That would just skip past a bare `=` (that is, where both name and value are empty).

**Comment by oalders** [comment]
I think that would work. It might be interesting to see what Mojo does in this case as well. Maybe we can get @karenetheridge, @skaji and @genio to comment on this.

**Comment by galenhuntington** [comment]
Actually, my proposal would still choke on `text/xml; =` (no semicolon at end).  So... maybe we should instead add `|| s/^=//` inside that `if`.  I think (hope) that covers all cases.  But yeah if anyone else wants to comment, please do.
