### ISSUE TITLE
HTTP::Request::Common and Changes should document when OPTIONS function was added

### ISSUE THREAD

**Issue by robrwo** [libwww-perl/HTTP-Message#177]
I think it was added sometime between 6.19 and 6.22. But this is not documented.

**Comment by simbabque** [comment]
It was 6.21 it seems. With Commit [dd1f6e2bfa1cd49d2c134aa0269226b752753712](https://github.com/libwww-perl/HTTP-Message/commit/dd1f6e2bfa1cd49d2c134aa0269226b752753712).

**Comment by neilb** [comment]
I think the Changes entry for 6.21 should be updated. I have often looked at the Changes file for a dist to work out the version I need to require. I've always assumed that other people do as well.

If you're ok with it, I'll submit a PR to update Changes and the doc for HTTP::Request::Common as well.

**Comment by robrwo** [comment]
Thanks for working on this.
