### ISSUE TITLE
Dependency on Clone -> non-reporting to CPANtesters

### ISSUE THREAD

**Issue by jkeenan** [libwww-perl/HTTP-Message#201]
This CPAN library is listed on metacpan as having a dependency on the Clone distribution.  That distribution is currently [FAILing on CPANtesters](http://www.cpantesters.org/cpan/report/c70621be-5c96-11ef-b179-cb1a840b22fd) due to a change in Perl 5 blead: the elimination of `'` from package and variable names.  That problem has been corrected in https://github.com/garu/Clone/issues/43 but a new CPAN release has not yet been issued.  Until such a new Clone release appears, distributions which depend on Clone will not be reached in dependency-order ("CPAN River") automated testing.  Such distributions will be classified `DISCARD`, *e.g.,*:
```
test DISCARD HTTP-Message-6.46 (perl-5.41.3) x86_64-linux 6.1.0-18-amd64
```
... and we will not be able to assess whether they are adversely affected by other changes in Perl 5 blead.

**Comment by jkeenan** [comment]
This will have knock-on effect on other CPAN distributions.  The following was just observed during a call to `test HTTP-Cookies`:
```
make_test NO 3 dependencies missing (HTTP::Headers::Util,HTTP::Request,HTTP::Response); additionally test harness failed
```

**Comment by karenetheridge** [comment]
A new version of Clone has now been uploaded.
