### ISSUE TITLE
lwp-download fails with HTTP::Message 6.06

### ISSUE THREAD

**Issue by njtaylor** [libwww-perl/HTTP-Message#3]
Found with WWW::YouTube::Download, youtube-download only reads first chunk of 4096 bytes.
Using HTTP::Message 6.04 the same download would work. Then tried with lwp-download the same thing happened.

With HTTP::Message 6.06

$ lwp-download 'http://www.youtube.com/watch?v=WLu1fi5FeOY&feature=g-all-xit' kk 
5.34 KB received  
Illegal field name 'X-Meta-Twitter:card' at /usr/local/libdata/perl5/site_perl/amd64-openbsd/HTML/HeadParser.pm line 207
Transfer aborted.  Delete kk? [n] 
Use of uninitialized value $length in numeric gt (>) at /usr/local/bin/lwp-download line 255, <STDIN> line 1.

$ sudo pkg_add -r p5-HTTP-Message
p5-HTTP-Message-6.06->6.04: ok
Read shared items: ok

$ rm kk
$ lwp-download 'http://www.youtube.com/watch?v=WLu1fi5FeOY&feature=g-all-xit' kk 
132 KB received  
$ 

$ curl -i -o kkk 'http://www.youtube.com/watch?v=WLu1fi5FeOY&feature=g-all-xit'  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  132k    0  132k    0     0   178k      0 --:--:-- --:--:-- --:--:--  193k
$ grep -i twitter:card kkk
    <meta name="twitter:card" value="player">
$ 

This is using libwww-perl 6.04
$ pkg_info | grep libwww
p5-LWP-Protocol-https-6.03 adds support for https to p5-libwww
p5-libwww-6.04      library for WWW access in Perl
$

**Comment by neilb** [comment]
I think this can be closed – HTTP header field names shouldn't ever include a colon, and all the examples above (which were 9 or so years ago) work fine now. Seems like people have stopped using broken field names?

**Comment by oalders** [comment]
Thanks, @neilb!
