### ISSUE TITLE
decoded_content isn't decoding charset if content-type is application/json

### ISSUE THREAD

**Issue by alambike** [libwww-perl/HTTP-Message#36]
In the same way that decoded_content makes charset decodification in text and xml content types, is not correct make this too in application/json ?

Something like (I'll make a PR if it is acceptable):

``` perl
if ($self->content_is_text || (my $is_xml = $self->content_is_xml) || (my $is_json = $self->content_is_json)) {
```

**Comment by vanHoesel** [comment]
See other issue
#72 (->decoded_content should decode application/json, etc [rt.cpan.org #82963])

See merge-request
#90 (Always charset decode, regardless of content type.)

### Conclusion

`decoded_content` SHOULD NOT decode using the charset given in the MIME type, but only for `text/*` types; `application/json` is binary data, and the charset param is only useful for a body-content processor, just as any param would be for any other binar format.

This issue SHOULD be closed

**Comment by dracos** [comment]
I assume you meant `SHOULD` at the start of your Conclusion?

**Comment by vanHoesel** [comment]
it says ... SHOULD NOT .. but only for `text/*`

**Comment by dracos** [comment]
Right, it does, but you *do* want to decode for `text/*`, surely?

**Comment by vanHoesel** [comment]
and we SHOULD only do it for that ... or be super intelligent guessing

**Comment by dracos** [comment]
Right; all I'm saying here is that your conclusion is incorrectly written for your argument, nothing more! :)

**Comment by vanHoesel** [comment]
as described in #99, unless we add extra parameters or an entire new method, this can not be solved without breaking any existing API based on JSON.

**Comment by oalders** [comment]
Closing this as we've got some progress in #99
