### ISSUE TITLE
HTTP method 'PATCH' not supported (rfc5789) [rt.cpan.org #80632]

### ISSUE THREAD

**Issue by oalders** [libwww-perl/HTTP-Message#53]
Migrated from [rt.cpan.org#80632](https://rt.cpan.org/Ticket/Display.html?id=80632) (status was 'new')

Requestors:
* MORITZ@cpan.org

From moritz@cpan.org on 2012-11-05 10:06:58:
```
RFC 5789 specifies a HTTP PATCH method, which some REST APIs and WebDAV
use, but HTTP::Message (and thus also LWP::UserAgent) doesn't support
it. It would be nice to have
```

**Comment by genio** [comment]
This has been corrected.
