### ISSUE TITLE
decoded_content / content_charset fails on Chinese websites since 6.04 [rt.cpan.org #95545]

### ISSUE THREAD

**Issue by oalders** [libwww-perl/HTTP-Message#58]
Migrated from [rt.cpan.org#95545](https://rt.cpan.org/Ticket/Display.html?id=95545) (status was 'new')

Requestors:
* ailin.nemui@gmail.com

From ailin.nemui@gmail.com on 2014-05-11 18:04:46:
```
The call to decoded_content / content_charset fails on Chinese websites
since 6.04  because it tries to call find_encoding("GB2312")->mime_name.
This is a valid encoding and returns a valid Encode::XS but
unfortunately the mime_name is undef.

Thanks

```

**Comment by eserte** [comment]
I think this is fixed in later Encode versions. Old Encode:
```
$ perl -MEncode -E 'say $Encode::VERSION; say Encode::find_encoding("GB2312")->mime_name' 
2.72

```
New Encode:
```
$ perl -MEncode -E 'say $Encode::VERSION; say Encode::find_encoding("GB2312")->mime_name'
3.01
EUC-CN
```
Possibly fixed in https://github.com/dankogai/p5-encode/commit/042b7806c0d38612bbe61b76d63bcb8898948a7c

**Comment by oalders** [comment]
Thanks @eserte! Currently we depend on Encode 2.21 (released 2007).  We should look at bumping that up.
