### ISSUE TITLE
HTTP::Status says 304 response is_redirect [rt.cpan.org #19243]

### ISSUE THREAD

**Issue by oalders** [libwww-perl/HTTP-Message#65]
Migrated from [rt.cpan.org#19243](https://rt.cpan.org/Ticket/Display.html?id=19243) (status was 'open')

Requestors:
* ryantate@ryantate.com

From  on 2006-05-14 01:17:49:
```
The 304 response header means "not modified," however HTTP::Status is
coded so that 304 is false for is_success and true for is_redirect. This
is clearly not a redirect, and also I would argue it is_success.

Ryan Tate
ryantate@ryantate.com
```

From  on 2006-05-14 01:19:46:
```
There is more information on the 304 header at:

http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.24

and

http://fishbowl.pastiche.org/2002/10/21/http_conditional_get_for_rss_hackers

RT
ryantate@ryantate.com
```

**Comment by vanHoesel** [comment]
[From RFC 7232 - HTTP/1.1 Conditional Requests](https://tools.ietf.org/html/rfc7232#section-4.1) where the **304** status code is defined:

> The `304 (Not Modified)` status code indicates that a conditional `GET` or `HEAD` request has been received and would have resulted in a `200 (OK)` response if it were not for the fact that the condition evaluated to false.  In other words, there is no need for the server to transfer a representation of the target resource because the request indicates that the client, which made the request conditional, already has a valid representation; the server is therefore **redirecting** the client to make use of that stored representation as if it were the payload of a 200 (OK) response.

The definitions of statuscode _ranges_ has been made carefully, and without any doubt, 304 is a redirect.

**Comment by oalders** [comment]
Thanks @vanHoesel!
