### ISSUE TITLE
allow header order to be adjusted

### ISSUE THREAD

**Issue by ghost** [libwww-perl/HTTP-Message#7]
i have come across a few sites that don't function properly when lwp sends the exact same headers as a browser does. the site works fine when the browser sends the same message, so i looked at the requests with wireshark and the only difference is the order of the headers. When I sent the message crafted with curl and the headers in the order that the browser sent, the request succeed.

please add ability for the user to adjust the order of the headers.

**Comment by oalders** [comment]
Closing since header order should not matter and this issue has seen no response from the original poster.

(Am wondering if perhaps there was a stray newline in the poster's headers that caused requests to fail in a specific order).
