### ISSUE TITLE
HTTP::Message::decodable should localise $@ [rt.cpan.org #116270]

### ISSUE THREAD

**Issue by oalders** [libwww-perl/HTTP-Message#80]
Migrated from [rt.cpan.org#116270](https://rt.cpan.org/Ticket/Display.html?id=116270) (status was 'open')

Requestors:
* 'spro^^*%*^6ut#@&$%*c

From $_ = 'spro^^*%*^6ut#@&$>#!^!#&!pan.org'; y/a-z.@//cd; print on 2016-07-18 06:21:49:
```

```

From $_ = 'spro^^*%*^6ut#@&$>#!^!#&!pan.org'; y/a-z.@//cd; print on 2016-07-18 06:22:18:
```

```

**Comment by simbabque** [comment]
The ticket had this comment with example code:

>     $ perl -MHTTP::Message -e '$m = new HTTP::Message; $@=57; $m->decodable; warn $@'
>     Warning: something's wrong at -e line 1.
> 
> It ate my 57!

**Comment by oalders** [comment]
Thanks -- that's much more helpful. 👍
