### ISSUE TITLE
Update perldoc for PATCH in HTTP::Request::Common 

### ISSUE THREAD

**Issue by saturdaywalkers** [libwww-perl/HTTP-Message#83]
Thanks for implementing HTTP PATCH!

Please update the perldoc to match
i.e. PATCH is like POST, not like PUT/GET

**Comment by oalders** [comment]
I think the docs are trying to convey that the `PATCH()` method has the same calling conventions as both `POST()` and `PUT()` methods, but we could certainly make this clearer.  A patch would be welcome.

**Comment by saturdaywalkers** [comment]
Fair enough :) 
I'll try. 
Time I gave something back.

**Comment by saturdaywalkers** [comment]
OK, done. There's a pull request. 
I fork'ed the repo, checked in my change, then did a pull request. Hope that's the correct process.

**Comment by genio** [comment]
Addressed in PR #84 
https://github.com/libwww-perl/HTTP-Message/pull/84
