### ISSUE TITLE
Feature Request: split_header_tokens()

### ISSUE THREAD

**Issue by FGasper** [libwww-perl/HTTP-Message#89]
`split_header_words()` is great for splitting apart header values like `foo=bar`, but for simple token lists there doesn’t seem to be logic readily available.

I’ve created a function and tests for this; would you be interested in having it in HTTP::Headers::Util?

**Comment by oalders** [comment]
@FGasper yes, sounds helpful.

**Comment by FGasper** [comment]
I’m actually going to close this.

Initially my use for this was as part of Net::WebSocket, but I ended up putting the implementation that I had into that module.

For potential future interest, though, my branch (with tests) is: https://github.com/FGasper/HTTP-Message/tree/89_split_header_tokens

**Comment by oalders** [comment]
Thanks, @FGasper!
